fix: Fix support for 3.8, 3.9, 3.10 (#16)
* fix: Fix support for 3.8, 3.9, 3.10

* Added UnprocessableEntityException to cover non-json responses

* ci: Make CI run linters and tests on push to main branch

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -77,6 +77,7 @@ jobs:
         run: poetry add "pydantic${{ matrix.pydantic-version }}"
       - name: Build coverage file
         run: |
+          set -e  # Stop the script if any command fails
           poetry run pytest --junitxml=pytest.xml --cov=src/declarativex tests/ | tee pytest-coverage.txt
       - name: Pytest coverage comment
         uses: MishaKav/pytest-coverage-comment@main
